### ISSUE TITLE
Definir telas

### ISSUE THREAD

**Issue by mikaellafs** [hericles-koelher/memento_studio#20]
- [x] Home
- [x] Buscar/filtrar baralhos privados
- [x] Buscar/filtrar baralhos públicos
- [x] Tela do baralho
- [x] Tela de cada card
- [x] Tela de sign in
- [x] Tela de sign up
- [ ] Tela de conta
- [ ] Tela de informações do app

**Comment by mikaellafs** [comment]
Algumas ideias:
![Telas-Memento-Studio drawio](https://user-images.githubusercontent.com/42984505/174697973-4624cd0e-1399-4c5a-90d2-55d8cbe1e84d.png)

**Comment by hericles-koelher** [comment]
Layout com algumas modificações e adições de telas:

![Telas-Memento-Studio drawio](https://user-images.githubusercontent.com/34146602/178045527-389c246a-b04a-4033-a4b1-5e57ba5501f3.png)
